services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ubatuba
      POSTGRES_PASSWORD: ubatuba_pass
      POSTGRES_DB: ubatuba_events
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "ubatu ba"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    env_file: backend/.env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/app/uploads:/app/uploads
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: ./frontend
    env_file: frontend/.env
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000

volumes:
  db_data:
